#pragma once
enum ROBOT_GLOBAL_NAVIGATION_STATE_ENUM {
  IDLE = 0,
  ROTATE = 1,
  MOVE = 2,
  MOVE_NEAR_POINT = 3,
  MOVE_PWM = 4,
  WHEEL_ALARM = 9
};

enum {LEFT, RIGHT};
enum {SPEED, PWM};

enum COMMAND_SOURCE_ENUM {
  GUI_ONLY = 0,
  NAVIGATION_ONLY = 1,
  MOVE_TO_DEATH_ONLY = 2,
  SEMI_AUTOMATIC = 3
};

enum Led {BATTERY=0, SENSOR=1, ALARM=2, BRAKE=3, HALL=4, SPEED_CONTROL=5, BRAKE_CONTROL=6,
     	CUTTER_ROTATION=7, CUTTER_LIFT=8, OZONIZER=9, BUMPER=10,
	LASER=11, PUMP=12, TANK=13, TELEOP_SPEED=14};

enum CutterControlCommand {
	LIFT_STOP = 0,
	LIFT_UP = 1,
	LIFT_DOWN = 2,
	CUTTING_MOVE_FORWARD = 3,
	CUTTING_MOVE_BACKWARD = 4,
	CUTTING_MOVE_STOP = 5,
	LIFT_SECONDS_UP = 6,
	LIFT_SECONDS_DOWN = 7
};
enum SpeedFlag{SPEED_I=1, SPEED_II=2, SPEED_III=4, SPEED_PWM=8};

enum Safety{
	OK, WARNING, STOP
};
enum class Metric{
	TARGET_SPEED, WHEEL_ODOMETRY, LIDAR_ODOMETRY, BATTERY
};

enum class LedStrip {NONE=0, LEFT=1, RIGHT=2, TOP=3};
enum Color {BLACK=0, BLUE=1, GREEN=2, AQUAMARINE=3, RED=4, PURPLE=5, YELLOW=6, WHITE=7};
